name: Build and Push Multi-Arch Images

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        run: |
          docker build --platform=local -o . git://github.com/docker/buildx
          mkdir -p ~/.docker/cli-plugins
          mv buildx ~/.docker/cli-plugins/docker-buildx
        shell: bash

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Extract Tag Name
        id: extract-tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | sed 's/refs\/tags\///')

      - name: Build and Push Multi-Arch Images
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t rossigee/update-dynamic-ip:${{ steps.extract-tag.outputs.tag }} .
          docker buildx imagetools inspect rossigee/update-dynamic-ip:${{ steps.extract-tag.outputs.tag }}
          docker push rossigee/update-dynamic-ip:${{ steps.extract-tag.outputs.tag }}
        env:
          DOCKER_CLI_AGGREGATE: "1"
        shell: bash
        working-directory: ${{ github.workspace }}
        continue-on-error: true
